# Generated by Django 5.1.7 on 2025-03-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='real_time_feedback',
            field=models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], default='nil', max_length=5),
            preserve_default=False,
        ),
    ]
