# Generated by Django 5.1.7 on 2025-03-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_message_real_time_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='real_time_feedback',
            field=models.CharField(choices=[('nil', 'NIL'), ('good', 'Good'), ('bad', 'Bad')], default='nil', max_length=5),
        ),
    ]
